# Generated by Django 4.1.3 on 2023-04-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archiverecord',
            options={'ordering': ['rec_date']},
        ),
        migrations.AlterModelOptions(
            name='forecastsrecord',
            options={'ordering': ['rec_date']},
        ),
    ]
