# Generated by Django 4.1.3 on 2023-04-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0003_rename_arch_date_archiverecord_arch_dt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatascraperLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_dt', models.DateTimeField()),
                ('log_str', models.CharField(max_length=100)),
            ],
        ),
    ]
