# Generated by Django 4.1.3 on 2022-11-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_date', models.DateTimeField()),
                ('feedbackers_name', models.CharField(max_length=100)),
                ('feedbackers_email', models.EmailField(max_length=254)),
                ('feedback_message', models.TextField()),
            ],
        ),
    ]
