# Generated by Django 4.1.3 on 2022-11-28 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForecastsRecord',
            new_name='Feedback',
        ),
    ]
